# Generated by Django 5.1.7 on 2025-03-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productsale'),
        ('transaction', '0008_bill_reason_bill_year_alter_debit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='credit',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
